VERSION = 9 # 8.2
FILE_VERSION = str(VERSION).replace('.','_')

TRAINING_DATA_VERSION = 9.1 # 8.2
TRAINING_DATA_FILE_VERSION = str(TRAINING_DATA_VERSION).replace('.','_')

TEST_DATA_VERSION = 9 # 8.2
TEST_DATA_FILE_VERSION = str(TEST_DATA_VERSION).replace('.','_')

PROJECTED_LINEUP_VERSION = 2
PROJECTED_LINEUP_FILE_VERSION = str(PROJECTED_LINEUP_VERSION).replace('.','_')

PROJECTED_LINEUP_TEST_DATA_VERSION = 2
PROJECTED_LINEUP_TEST_DATA_FILE_VERSION = str(PROJECTED_LINEUP_TEST_DATA_VERSION).replace('.','_')

H2O_VERSION = 7.1
H2O_FILE_VERSION = str(H2O_VERSION).replace('.','_')

TORCH_VERSION = 9
TORCH_FILE_VERSION = str(TORCH_VERSION).replace('.','_')

XGB_VERSION = 9.3
XGB_FILE_VERSION = str(XGB_VERSION).replace('.','_')

XGB_TEAM_VERSION = 9.3
XGB_TEAM_FILE_VERSION = str(XGB_TEAM_VERSION).replace('.','_')

LGBM_TEAM_VERSION = 9
LGBM_TEAM_FILE_VERSION = str(VERSION).replace('.','_')

TEAM_VERSION = 9.3
TEAM_FILE_VERSION = str(TEAM_VERSION).replace('.','_')

MLB_VERSION = 1.1
FILE_MLB_VERSION = str(MLB_VERSION).replace('.','_')
MLB_FILE_VERSION = str(MLB_VERSION).replace('.','_')

MLB_TEAM_VERSION = 1
MLB_TEAM_FILE_VERSION = str(MLB_TEAM_VERSION).replace('.','_')

MLB_LGBM_VERSION = 1.1
MLB_LGBM_FILE_VERSION = str(MLB_LGBM_VERSION).replace('.','_')

MLB_LGBM_TEAM_VERSION = 1
MLB_LGBM_TEAM_FILE_VERSION = str(MLB_LGBM_TEAM_VERSION).replace('.','_')

MLB_CAT_VERSION = 1.1
MLB_CAT_FILE_VERSION = str(MLB_CAT_VERSION).replace('.','_')

MLB_CAT_TEAM_VERSION = 1
MLB_CAT_TEAM_FILE_VERSION = str(MLB_CAT_TEAM_VERSION).replace('.','_')



RANDOM_STATE = 12
VERBOSE = 1
FLIP_R = False
FLIP_B = False

# START_SEASON = 20172018
# START_SEASON = 20212022
START_SEASON = 20042005
# START_SEASON = 20152016
# START_SEASON = 20002001
END_SEASON = 20222023
# END_SEASON = 20232024