
TEAM_IDS = [108,109,110,111,112,113,114,115,116,117,118,119,120,121,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,158]


def team_lookup(db,only_active_mlb=False):
  Teams = db['teams']
  if only_active_mlb:
    teams = list(Teams.find({'sport.name':'Major League Baseball','active':True},{'_id': 0}))
  else:
    teams = list(Teams.find({},{'_id': 0}))
  team_lookup = {}
  for team in teams:
    team_lookup[team['id']] = {
      'name':team['name'],
      'abbrev':team['abbreviation'],
      'code':team['teamCode'],
      'league':{'name':team['league']['name'],'id':team['league']['id'] if 'id' in team['league'] else 'N/A'},
      'division':{'name':team['division']['name'],'id':team['division']['id'] if 'id' in team['division'] else 'N/A'},
      'sport':{'name':team['sport']['name'],'id':team['sport']['id'] if 'id' in team['sport'] else 'N/A'},
      'franchiseName':team['franchiseName'],
      'clubName':team['clubName'],
      'active':team['active'],
    }
  return team_lookup


home_rename = {
  'homeTeam': 'team',
  'awayTeam': 'opponent',
  'homeScore': 'score',
  'awayScore': 'opponentScore',
  'homeBatters': 'batters',
  'homePitchers': 'pitchers',
  'homeBench': 'bench',
  'homeBullpen': 'bullpen',
  'homeBatter1': 'batter1',
  'homeBatter2': 'batter2',
  'homeBatter3': 'batter3',
  'homeBatter4': 'batter4',
  'homeBatter5': 'batter5',
  'homeBatter6': 'batter6',
  'homeBatter7': 'batter7',
  'homeBatter8': 'batter8',
  'homeBatter9': 'batter9',
  'homePitcher': 'pitcher',
  'homeCatcher': 'catcher',
  'homeFirstBase': 'firstBase',
  'homeSecondBase': 'secondBase',
  'homeThirdBase': 'thirdBase',
  'homeShortstop': 'shortstop',
  'homeLeftField': 'leftField',
  'homeCenterField': 'centerField',
  'homeRightField': 'rightField',
  'homeDH': 'dh',
  'awayBatters': 'opponentBatters',
  'awayPitchers': 'opponentPitchers',
  'awayBench': 'opponentBench',
  'awayBullpen': 'opponentBullpen',
  'awayBatter1': 'opponentBatter1',
  'awayBatter2': 'opponentBatter2',
  'awayBatter3': 'opponentBatter3',
  'awayBatter4': 'opponentBatter4',
  'awayBatter5': 'opponentBatter5',
  'awayBatter6': 'opponentBatter6',
  'awayBatter7': 'opponentBatter7',
  'awayBatter8': 'opponentBatter8',
  'awayBatter9': 'opponentBatter9',
  'awayPitcher': 'opponentPitcher',
  'awayCatcher': 'opponentCatcher',
  'awayFirstBase': 'opponentFirstBase',
  'awaySecondBase': 'opponentSecondBase',
  'awayThirdBase': 'opponentThirdBase',
  'awayShortstop': 'opponentShortstop',
  'awayLeftField': 'opponentLeftField',
  'awayCenterField': 'opponentCenterField',
  'awayRightField': 'opponentRightField',
  'awayDH': 'opponentDH',
}
away_rename = {
  'homeTeam': 'opponent',
  'awayTeam': 'team',
  'homeScore': 'opponentScore',
  'awayScore': 'score',
  'awayBatters': 'batters',
  'awayPitchers': 'pitchers',
  'awayBench': 'bench',
  'awayBullpen': 'bullpen',
  'awayBatter1': 'batter1',
  'awayBatter2': 'batter2',
  'awayBatter3': 'batter3',
  'awayBatter4': 'batter4',
  'awayBatter5': 'batter5',
  'awayBatter6': 'batter6',
  'awayBatter7': 'batter7',
  'awayBatter8': 'batter8',
  'awayBatter9': 'batter9',
  'awayPitcher': 'pitcher',
  'awayCatcher': 'catcher',
  'awayFirstBase': 'firstBase',
  'awaySecondBase': 'secondBase',
  'awayThirdBase': 'thirdBase',
  'awayShortstop': 'shortstop',
  'awayLeftField': 'leftField',
  'awayCenterField': 'centerField',
  'awayRightField': 'rightField',
  'awayDH': 'dh',
  'homeBatters': 'opponentBatters',
  'homePitchers': 'opponentPitchers',
  'homeBench': 'opponentBench',
  'homeBullpen': 'opponentBullpen',
  'homeBatter1': 'opponentBatter1',
  'homeBatter2': 'opponentBatter2',
  'homeBatter3': 'opponentBatter3',
  'homeBatter4': 'opponentBatter4',
  'homeBatter5': 'opponentBatter5',
  'homeBatter6': 'opponentBatter6',
  'homeBatter7': 'opponentBatter7',
  'homeBatter8': 'opponentBatter8',
  'homeBatter9': 'opponentBatter9',
  'homePitcher': 'opponentPitcher',
  'homeCatcher': 'opponentCatcher',
  'homeFirstBase': 'opponentFirstBase',
  'homeSecondBase': 'opponentSecondBase',
  'homeThirdBase': 'opponentThirdBase',
  'homeShortstop': 'opponentShortstop',
  'homeLeftField': 'opponentLeftField',
  'homeCenterField': 'opponentCenterField',
  'homeRightField': 'opponentRightField',
  'homeDH': 'opponentDH',
}
