import sys
sys.path.append(r'C:\Users\syncc\code\Hockey API\hockey-api\util')

from util.helpers import safe_chain, getPlayer, getAge, n2n, b2n


def base_inputs(db,awayTeam,homeTeam,game,gi,startTime,date):
  return {
    'id': safe_chain(game,'id'),
    'season': safe_chain(game,'season'),
    'gameType': safe_chain(game,'gameType'),
    'venue': n2n(safe_chain(game,'venue','default')),
    'neutralSite': b2n(safe_chain(game,'neutralSite')),
    'homeTeam': homeTeam['id'],
    'awayTeam': awayTeam['id'],
    'homeScore': safe_chain(homeTeam,'score'),
    'awayScore': safe_chain(awayTeam,'score'),
    'totalGoals': safe_chain(homeTeam,'score') + safe_chain(awayTeam,'score'),
    'goalDifferential': safe_chain(homeTeam,'score') - safe_chain(awayTeam,'score') if safe_chain(homeTeam,'score') >= safe_chain(awayTeam,'score') else safe_chain(awayTeam,'score') - safe_chain(homeTeam,'score'),
    'winner': homeTeam['id'] if safe_chain(homeTeam,'score') > safe_chain(awayTeam,'score') else awayTeam['id'],
    'startTime': startTime,
    'date': date,
    'awayHeadCoach': n2n(safe_chain(gi,'awayTeam','headCoach','default')),
    'homeHeadCoach': n2n(safe_chain(gi,'homeTeam','headCoach','default')),
    'ref1': n2n(safe_chain(gi,'referees',0,'default')),
    'ref2': n2n(safe_chain(gi,'referees',1,'default')),
    'linesman1': n2n(safe_chain(gi,'linesmen',0,'default')),
    'linesman2': n2n(safe_chain(gi,'linesmen',1,'default')),
    'finalPeriod': safe_chain(game,'period'),
    'awayShots': safe_chain(game,'awayTeam','sog'),
    'homeShots': safe_chain(game,'homeTeam','sog'),
    'awayShotsPeriod1': safe_chain(game,'boxscore','shotsByPeriod',0,'away'),
    'homeShotsPeriod1': safe_chain(game,'boxscore','shotsByPeriod',0,'home'),
    'awayShotsPeriod2': safe_chain(game,'boxscore','shotsByPeriod',1,'away'),
    'homeShotsPeriod2': safe_chain(game,'boxscore','shotsByPeriod',1,'home'),
    'awayShotsPeriod3': safe_chain(game,'boxscore','shotsByPeriod',2,'away'),
    'homeShotsPeriod3': safe_chain(game,'boxscore','shotsByPeriod',2,'home'),
    'awayShotsPeriod4': safe_chain(game,'boxscore','shotsByPeriod',3,'away'),
    'homeShotsPeriod4': safe_chain(game,'boxscore','shotsByPeriod',3,'home'),
    'awayShotsPeriod5': safe_chain(game,'boxscore','shotsByPeriod',4,'away'),
    'homeShotsPeriod5': safe_chain(game,'boxscore','shotsByPeriod',4,'home'),
    'awayScorePeriod1': safe_chain(game,'boxscore','linescore','byPeriod',0,'away'),
    'homeScorePeriod1': safe_chain(game,'boxscore','linescore','byPeriod',0,'home'),
    'awayScorePeriod2': safe_chain(game,'boxscore','linescore','byPeriod',1,'away'),
    'homeScorePeriod2': safe_chain(game,'boxscore','linescore','byPeriod',1,'home'),
    'awayScorePeriod3': safe_chain(game,'boxscore','linescore','byPeriod',2,'away'),
    'homeScorePeriod3': safe_chain(game,'boxscore','linescore','byPeriod',2,'home'),
    'awayScorePeriod4': safe_chain(game,'boxscore','linescore','byPeriod',3,'away'),
    'homeScorePeriod4': safe_chain(game,'boxscore','linescore','byPeriod',3,'home'),
    'awayScorePeriod5': safe_chain(game,'boxscore','linescore','byPeriod',4,'away'),
    'homeScorePeriod5': safe_chain(game,'boxscore','linescore','byPeriod',4,'home'),
    'period1PuckLine': abs(safe_chain(game,'boxscore','linescore','byPeriod',0,'away') - safe_chain(game,'boxscore','linescore','byPeriod',0,'home')),
    'period2PuckLine': abs(safe_chain(game,'boxscore','linescore','byPeriod',1,'away') - safe_chain(game,'boxscore','linescore','byPeriod',1,'home')),
    'period3PuckLine': abs(safe_chain(game,'boxscore','linescore','byPeriod',2,'away') - safe_chain(game,'boxscore','linescore','byPeriod',2,'home')),
  }