

home_rename = {
  'homeTeam': 'team',
  'awayTeam': 'opponent',
  'homeScore': 'score',
  'awayScore': 'opponentScore',
  'homeHeadCoach': 'headCoach',
  'awayHeadCoach': 'opponentHeadCoach',
  'homeForwardAverage': 'forwardAverage',
  'homeDefenseAverage': 'defenseAverage',
  'homeGoalieAverage': 'goalieAverage',
  'awayForwardAverage': 'opponentForwardAverage',
  'awayDefenseAverage': 'opponentDefenseAverage',
  'awayGoalieAverage': 'opponentGoalieAverage',
  'homeForwardAverageAge': 'forwardAverageAge',
  'homeDefenseAverageAge': 'defenseAverageAge',
  'homeGoalieAverageAge': 'goalieAverageAge',
  'awayForwardAverageAge': 'opponentForwardAverageAge',
  'awayDefenseAverageAge': 'opponentDefenseAverageAge',
  'awayGoalieAverageAge': 'opponentGoalieAverageAge',
  'winner': 'win',
  'winnerB': 'winB',
}
away_rename = {
  'homeTeam': 'opponent',
  'awayTeam': 'team',
  'homeScore': 'opponentScore',
  'awayScore': 'score',
  'homeHeadCoach': 'opponentHeadCoach',
  'awayHeadCoach': 'headCoach',
  'homeForwardAverage': 'opponentForwardAverage',
  'homeDefenseAverage': 'opponentDefenseAverage',
  'homeGoalieAverage': 'opponentGoalieAverage',
  'awayForwardAverage': 'forwardAverage',
  'awayDefenseAverage': 'defenseAverage',
  'awayGoalieAverage': 'goalieAverage',
  'homeForwardAverageAge': 'opponentForwardAverageAge',
  'homeDefenseAverageAge': 'opponentDefenseAverageAge',
  'homeGoalieAverageAge': 'opponentGoalieAverageAge',
  'awayForwardAverageAge': 'forwardAverageAge',
  'awayDefenseAverageAge': 'defenseAverageAge',
  'awayGoalieAverageAge': 'goalieAverageAge',
  'winner': 'win',
  'winnerB': 'winB',
}